development:
  adapter: postgresql
  database: studyfiles_development
  username: postgres
  password: qweqwe
  encoding: utf8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: studyfiles_test
  username: postgres
  password: qweqwe
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: studyfiles
  username: postgres
  pool: 5
  timeout: 5000
