development:
  sql_range_step: 10000000
  enable_star: 1
  min_infix_len: 1
  morphology: stem_en
  mem_limit: 128M
  max_matches: 25000
  port: 9313

test:
  enable_star: 1
  min_infix_len: 1
  port: 9333

production:
  sql_range_step: 10000000
  enable_star: 1
  min_infix_len: 1
  morphology: stem_en
  mem_limit: 128M
  max_matches: 500
  port: 9313
  searchd_file_path: "/var/www/studyfiles/shared/sphinx"
  config_file: "/var/www/studyfiles/current/config/production.sphinx.conf"
  searchd_log_file: "/var/www/studyfiles/current/log/searchd.log"
  query_log_file: "/var/www/studyfiles/current/log/searchd.query.log"
  bin_path: "/var/www/studyfiles/shared/sphinx/bin"
  pid_file: "/var/www/studyfiles/current/tmp/pids/searchd.production.pid"
